### ISSUE TITLE
Licenses are not being detected accurately

### ISSUE THREAD

**Issue by ViralBShah** [JuliaDocs/DocumentationGenerator.jl#26]
Many MIT licenses are being detected as Other.

Example: DataFrames.

**Comment by pfitzseb** [comment]
This is happening because [licensee](https://github.com/licensee/licensee) isn't detecting Pkg2-generated licenses correctly -- Github itself uses the same gem and doesn't show the license type at https://github.com/licensee/licensee either.

Short term we probably should remove the `>` quotes and run `licensee` ourselves (or maybe we already do this, @vdayanand?). Long term it might be good to fix the gem to handle this case.

**Comment by vdayanand** [comment]
We have fixed this, and will be part of the next deployment
