### ISSUE TITLE
The logo is not correctly rendered for Yao.jl

### ISSUE THREAD

**Issue by Roger-luo** [JuliaDocs/DocumentationGenerator.jl#46]
check this link: https://pkg.julialang.org/docs/Yao/TDiQQ/0.4.2/

PS. will `pkg.julialang.org` only render the README? I thought it will provide the documentation as well, but it seems all of our doc string is missing at the moment in pkg.julialang.org, and if I just search our example, it won't appear...

**Comment by pfitzseb** [comment]
It should render your actual docs indeed -- I suspect we had some spurious issue when generating the docs (https://github.com/JuliaDocs/DocumentationGenerator.jl/pull/36 might help though, once merged and deployed, because it allows you to specify already built URLs). 

The missing image (and generally bad readme rendering) is fixed with https://github.com/JuliaDocs/DocumentationGenerator.jl/pull/42, which should arrive downstream soonish.
